#!/bin/sh

#    -rotate to inverted 

    xrandr -o inverted 
#    xsetwacom set $stylus rotate HALF 
#    xsetwacom set $touch rotate HALF 
#    xsetwacom set $eraser rotate HALF 

    xsetwacom set 'Wacom ISDv4 E3 Pen stylus' rotate HALF
    xsetwacom set 'Wacom ISDv4 E3 Finger touch' rotate HALF
    xsetwacom set 'Wacom ISDv4 E3 Pen eraser' rotate HALF

# xinput set-prop 'SynPS/2 Synaptics TouchPad' 'Device Enabled' false

synclient TouchpadOff=1

ln -sf /home/pit/scripts/hprotinvert /home/pit/scripts/lastrot
