#!/bin/sh 

#    -rotate to normal 

    xrandr -o normal 
#    xsetwacom set $stylus rotate NONE 
#   xsetwacom set $touch rotate NONE 
#   xset 'Wacom ISDv4 E3 Pen stylus' rotate NONE
    xsetwacom set 'Wacom ISDv4 E3 Finger touch' rotate NONE
    xsetwacom set $eraser rotate NONE 

    xsetwacom set 'Wacom ISDv4 E3 Pen eraser' rotate NONE

# xinput set-prop 'SynPS/2 Synaptics TouchPad' 'Device Enabled' 1

synclient TouchpadOff=0

ln -sf /home/pit/scripts/hprotnorm /home/pit/scripts/lastrot
ln -sf /home/pit/scripts/hprotleft /home/pit/scripts/nextrot


